In [1]:
import pandas as pd
import numpy as np

In [2]:
entities_file_path = "/home/Nema/UniCRS_GraphRAG/GraphRAG/output/successful_20250129-110435/artifacts/create_final_entities.parquet"
relationship_file_path = "/home/Nema/UniCRS_GraphRAG/GraphRAG/output/successful_20250129-110435/artifacts/create_final_relationships.parquet"
entities_df = pd.read_parquet(entities_file_path)
relationship_df = pd.read_parquet(relationship_file_path)

In [5]:
print(entities_df['type'].value_counts())
entities_df

type
MOVIE                 7413
                      1876
ACTOR                 1240
GENRE                  680
DIRECTOR               328
CHARACTER               24
COMEDY                  11
SONG                     6
HORROR                   5
AUTHOR                   4
ANIMATED                 4
ACTION                   3
ROMANTIC COMEDY          3
THRILLER                 3
TV SHOW                  3
RECOMMENDATION           3
SPORTS DOCUMENTARY       3
WESTERN                  3
DRAMA                    3
RELATIONSHIP             2
NOVEL                    2
TYPE                     2
LOCATION                 2
COMPOSER                 2
THE MASK (1994)          1
VEHICLE                  1
INSIDIOUS (2011)         1
UNKNOWN                  1
THE ROCK                 1
CHEF                     1
FOREIGN FILM             1
SCIFI                    1
YEAR                     1
SCIENCE FICTION          1
TV SERIES                1
VARIATIONS               1
FANTASY                  1
MARK WAHLBERG            1
BAND                     1
MELISSA MCCARTHY         1
AUDIENCE                 1
A WRINKLE IN TIME        1
TENNIS PLAYER            1
MUSIC                    1
ACTRESS                  1
SUPERHERO                1
ODDBALL                  1
SPANISH                  1
BRUCE WILLIS             1
MYSTERY                  1
FUNNY ROMANTIC           1
FAMILY                   1
HUMOR                    1
Name: count, dtype: int64

,id,human_readable_id,title,type,description,text_unit_ids
0,e4adb8af-2687-4e59-b5a9-8ad0fda5d639,0,SUPER TROOPERS (2001),MOVIE,"""Super Troopers (2001)"" is a comedy film direc...",[d227fc210131fb643e0f78a9511e1f40f55813b90b15d...
1,6ea22bff-cfdf-4c87-be54-191a3fc3bcf4,1,POLICE ACADEMY (1984),MOVIE,"The entity ""POLICE ACADEMY (1984)"" is a 1984 c...",[d227fc210131fb643e0f78a9511e1f40f55813b90b15d...
2,2510d6d3-fb63-4fe2-b354-ccc649859c74,2,AMERICAN PIE (1999),MOVIE,"""AMERICAN PIE (1999)"" is a 1999 comedy movie t...",[d227fc210131fb643e0f78a9511e1f40f55813b90b15d...
3,7a50c139-cfe5-4e63-96c3-80a0299188c4,3,POLICE ACADEMY 2: THEIR FIRST ASSIGNMENT (1985),MOVIE,"""POLICE ACADEMY 2: THEIR FIRST ASSIGNMENT (198...",[d227fc210131fb643e0f78a9511e1f40f55813b90b15d...
4,db466a7c-9810-4254-bc0d-3f79db4a2c37,4,LETHAL WEAPON (1987),MOVIE,"""Lethal Weapon (1987)"" is a 1987 action comedy...",[d227fc210131fb643e0f78a9511e1f40f55813b90b15d...
...,...,...,...,...,...,...
11649,1da15402-f6f3-4471-b447-9badd1e4d488,11649,JOHN CASSAVETES,ACTOR,Actor in Rosemary's Baby (1968),[b2b6b93bc5878b4c33959d0cecb88ec63671a6eda6b0a...
11650,814f94a5-292f-4e39-a669-fcd15c1cbec0,11650,FULLMETAL ALCHEMIST,MOVIE,A movie based on the popular anime and manga s...,[b2b6b93bc5878b4c33959d0cecb88ec63671a6eda6b0a...
11651,6f3f4f07-fe34-4574-9caa-17cb2a6eb933,11651,RAMPAGE,MOVIE,A 2018 action movie based on the video game,[b2b6b93bc5878b4c33959d0cecb88ec63671a6eda6b0a...
11652,8e219c95-cd93-4658-80e9-7b24bc42e631,11652,AVENGERS INFINITY WAR,MOVIE,A 2018 superhero movie featuring the Avengers,[b2b6b93bc5878b4c33959d0cecb88ec63671a6eda6b0a...
11653,80c5d840-67ca-4f13-8a34-f82f918a1888,11653,IN CINEMAS,GENRE,Movies watched in theaters,[3d09ef22b6cb4a5b3faf0b482dc55c53780a3e2e35c50...

In [6]:
relationship_df

,id,human_readable_id,source,target,description,weight,combined_degree,text_unit_ids
0,1ef8b2a1-6a3d-4090-9db1-30464517ed34,0,SUPER TROOPERS (2001),POLICE ACADEMY (1984),Both movies are comedy movies),1.0,46,[d227fc210131fb643e0f78a9511e1f40f55813b90b15d...
1,8525e8e0-8e7d-4ca6-85f3-8be5dc63f744,1,POLICE ACADEMY (1984),POLICE ACADEMY 2: THEIR FIRST ASSIGNMENT (1985),Both movies are comedy movies),1.0,19,[d227fc210131fb643e0f78a9511e1f40f55813b90b15d...
2,1c626956-3842-4efe-beb3-53fe5a462e2e,2,A NIGHTMARE ON ELM STREET (1984),HAPPY DEATH DAY (2017),Both movies are horror movies),2.0,88,[d227fc210131fb643e0f78a9511e1f40f55813b90b15d...
3,4770de55-4db9-4b0c-976c-c0edde4f8a23,3,THE LAST HOUSE ON THE LEFT (1972),THE FOREST (2016),Both movies are horror movies),2.0,10,[d227fc210131fb643e0f78a9511e1f40f55813b90b15d...
4,7dd8c7b4-d2c8-42e9-b1e2-7f2c198e832f,4,HOT TUB TIME MACHINE,IDENTITY THIEF (2013),Both movies are comedy movies),2.0,26,[d227fc210131fb643e0f78a9511e1f40f55813b90b15d...
...,...,...,...,...,...,...,...,...
32140,a362c786-c43b-43ef-a9b1-1db80ef82698,32140,STAR WARS,SOUNDTRACK,User liked the soundtrack of Star Wars),2.0,85,[3d09ef22b6cb4a5b3faf0b482dc55c53780a3e2e35c50...
32141,0bc602fb-795f-4600-a958-896a69aa4e7d,32141,STAR WARS,GUARDIANS OF THE GALAXY (2014),Guardians of the Galaxy is recommended for Sta...,2.0,159,[3d09ef22b6cb4a5b3faf0b482dc55c53780a3e2e35c50...
32142,c408c124-bf6b-476b-adf0-8d174247400a,32142,STAR WARS,KINGSMAN: THE GOLDEN CIRCLE,User mentioned Kingsman: The Golden Circle),2.0,89,[3d09ef22b6cb4a5b3faf0b482dc55c53780a3e2e35c50...
32143,38ef5e6f-52f6-4770-8944-b943910b7695,32143,IN CINEMAS,INCREDIBLES 2 (2018),Incredibles 2 was watched in theaters),2.0,24,[3d09ef22b6cb4a5b3faf0b482dc55c53780a3e2e35c50...
32144,525e9799-7b89-477f-822f-22cde6f9955b,32144,IN CINEMAS,MOTHER! (2017),Mother! was watched in theaters),2.0,31,[3d09ef22b6cb4a5b3faf0b482dc55c53780a3e2e35c50...

In [3]:
# Prepare mappings for entities
entity_id_map = dict(zip(entities_df['title'], entities_df['human_readable_id']))
entity_type_map = dict(zip(entities_df['title'], entities_df['type']))

# Create Relationships DataFrame with initial mappings
relationships_clean_df = relationship_df.assign(
    entity_id_source=relationship_df['source'].map(entity_id_map),
    entity_type_source=relationship_df['source'].map(entity_type_map),
    entity_id_target=relationship_df['target'].map(entity_id_map),
    entity_type_target=relationship_df['target'].map(entity_type_map)
)

# Define relationship type mapping with IDs
relationship_type_mapping = {
    ('MOVIE', 'ACTOR'): ('features', 1),
    ('ACTOR', 'MOVIE'): ('acted_in', 2),
    ('MOVIE', 'GENRE'): ('belongs_to_genre', 3),
    ('GENRE', 'MOVIE'): ('categorizes', 4),
    ('MOVIE', 'DIRECTOR'): ('directed_by', 5),
    ('DIRECTOR', 'MOVIE'): ('directed', 6),
    ('MOVIE', 'CHARACTER'): ('has_character', 7),
    ('CHARACTER', 'MOVIE'): ('featured_in', 8),
    ('ACTOR', 'CHARACTER'): ('portrays', 9),
    ('CHARACTER', 'ACTOR'): ('portrayed_by', 10),
    ('GENRE', 'DIRECTOR'): ('prefers_to_direct', 11),
    ('DIRECTOR', 'GENRE'): ('has_preference_for', 12),
    ('CHARACTER', 'DIRECTOR'): ('created_by', 13),
    ('DIRECTOR', 'CHARACTER'): ('conceived', 14),
    ('MOVIE', 'MOVIE'): ('similar', 15)
}

# Reverse the relationships and add them to the original DataFrame
relationships_reversed_df = relationships_clean_df.rename(columns={
    'entity_id_source': 'entity_id_target',
    'entity_name_source': 'entity_name_target',
    'entity_type_source': 'entity_type_target',
    'entity_id_target': 'entity_id_source',
    'entity_name_target': 'entity_name_source',
    'entity_type_target': 'entity_type_source'
}).copy()

# Combine the original and reversed relationships
relationships_combined_df = pd.concat([relationships_clean_df, relationships_reversed_df], ignore_index=True)

# Assign relationship types and IDs based on source and target entity types
relationships_combined_df[['relationship_type', 'relationship_type_id']] = relationships_combined_df.apply(
    lambda row: pd.Series(relationship_type_mapping.get(
        (row['entity_type_source'], row['entity_type_target']), ('unknown', -1)
    )),
    axis=1
)

In [4]:
kg_df = relationships_combined_df[['entity_id_source', 'source', 'entity_type_source',  'entity_id_target', 'target', 'entity_type_target', 'relationship_type', 'relationship_type_id']]

In [9]:
print(kg_df['relationship_type'].value_counts())
kg_df

relationship_type
unknown               30262
similar               17942
acted_in               4198
features               4198
belongs_to_genre       2839
categorizes            2839
directed_by             963
directed                963
prefers_to_direct        26
has_preference_for       26
has_character            16
featured_in              16
portrayed_by              1
portrays                  1
Name: count, dtype: int64

,entity_id_source,source,entity_type_source,entity_id_target,target,entity_type_target,relationship_type,relationship_type_id
0,0,SUPER TROOPERS (2001),MOVIE,1,POLICE ACADEMY (1984),MOVIE,similar,15
1,1,POLICE ACADEMY (1984),MOVIE,3,POLICE ACADEMY 2: THEIR FIRST ASSIGNMENT (1985),MOVIE,similar,15
2,7,A NIGHTMARE ON ELM STREET (1984),MOVIE,8,HAPPY DEATH DAY (2017),MOVIE,similar,15
3,9,THE LAST HOUSE ON THE LEFT (1972),MOVIE,12,THE FOREST (2016),MOVIE,similar,15
4,13,HOT TUB TIME MACHINE,MOVIE,14,IDENTITY THIEF (2013),MOVIE,similar,15
...,...,...,...,...,...,...,...,...
64285,735,STAR WARS,,619,SOUNDTRACK,MOVIE,unknown,-1
64286,148,STAR WARS,MOVIE,619,GUARDIANS OF THE GALAXY (2014),MOVIE,similar,15
64287,3851,STAR WARS,MOVIE,619,KINGSMAN: THE GOLDEN CIRCLE,MOVIE,similar,15
64288,457,IN CINEMAS,MOVIE,11653,INCREDIBLES 2 (2018),GENRE,belongs_to_genre,3
64289,3933,IN CINEMAS,MOVIE,11653,MOTHER! (2017),GENRE,belongs_to_genre,3

In [13]:
kg_df.to_csv('/home/Nema/UniCRS_GraphRAG/GraphRAG/output/20250119-161611/artifacts/kg.csv')

#### 1. dbpedia_subkg.json

In [14]:
from collections import defaultdict
import json

# Group data by source entity
json_structure = defaultdict(list)

# Replace 'kg_df' with the DataFrame containing the KG relationships
for _, row in kg_df.iterrows():
    source_id = row['entity_id_source']
    target_id = row['entity_id_target']
    relationship_id = row['relationship_type_id']
    if relationship_id != -1:  # Only include valid relationships
        json_structure[source_id].append([relationship_id, target_id])

# Convert the defaultdict to a regular dictionary
json_output = {str(source): [[rel_id, target] for rel_id, target in targets]
               for source, targets in json_structure.items()}

# Save the compact JSON structure to a file
compact_json_file_path = "/home/Nema/UniCRS_GraphRAG/GraphRAG/dbpedia_subkg.json"
with open(compact_json_file_path, "w") as json_file:
    json.dump(json_output, json_file, separators=(',', ':'))

#### 2. entity2id.json

In [21]:
# Create a mapping of entity: id in the required format
entity_id_mapping = {
    f"{row['title']}" : row['human_readable_id']
    for _, row in entities_df.iterrows()
}

# Save the mapping as a JSON file
entity_json_file_path = "/home/Nema/UniCRS_GraphRAG/GraphRAG/entity2id.json"
with open(entity_json_file_path, "w") as json_file:
    json.dump(entity_id_mapping, json_file, separators=(',', ':'))

#### 3. relation2id.json

In [23]:
# Create a mapping of relationship_type: id
relationship_type_id_mapping = {relation: rel_id for _, (relation, rel_id) in relationship_type_mapping.items()}

# Save the mapping as a JSON file
relationship_json_file_path = "/home/Nema/UniCRS_GraphRAG/GraphRAG/relation2id.json"
with open(relationship_json_file_path, "w") as json_file:
    json.dump(relationship_type_id_mapping, json_file, separators=(',', ':'))

In [6]:
import json 
# Get unique relationship types
unique_relationships = kg_df['relationship_type'].unique()

# Remove any None or NaN values if they exist
unique_relationships = [rel for rel in unique_relationships if pd.notna(rel)]

# Sort relationships alphabetically for consistency
unique_relationships.sort()

# Create mapping starting from ID 1
relationship_mapping = {rel: idx + 1 for idx, rel in enumerate(unique_relationships)}

# Save mapping to JSON file
with open('/home/Nema/UniCRS_GraphRAG/GraphRAG/new_relation2id.json', 'w') as f:
    json.dump(relationship_mapping, f, indent=2)

#### 4. item_ids.json

In [7]:
import json
import re
import html
from tqdm.auto import tqdm

# Regular expression to match movie IDs in text
movie_pattern = re.compile(r'@\d+')

def simplify_and_normalize(name):
    """Simplifies and normalizes entity or movie names."""
    # Replace underscores with spaces, convert to lowercase, and remove parenthetical text
    name = name.replace("_", " ").lower()
    name = re.sub(r"\s*\(.*?\)", "", name).strip()
    return name

def match_entity_by_name(name, entity_name_map):
    """
    Find a matching entity in entity_name_map using substring matching.
    Returns the entity ID instead of the name.
    """
    simplified_name = simplify_and_normalize(name)
    for entity, entity_id in entity_name_map.items():
        normalized_entity = simplify_and_normalize(entity)
        if simplified_name in normalized_entity:  # Substring matching
            return entity_id
    return None

def process_utt(utt, movieid2name, replace_movieId):
    """
    Replaces movie IDs in text with their corresponding names, normalizing the text.
    """
    def convert(match):
        movieid = match.group(0)[1:]
        if movieid in movieid2name:
            movie_name = movieid2name[movieid]
            movie_name = ' '.join(movie_name.split())
            return movie_name
        else:
            return match.group(0)

    if replace_movieId:
        utt = re.sub(movie_pattern, convert, utt)
    utt = ' '.join(utt.split())
    utt = html.unescape(utt)

    return utt

def process(data_file, out_file, movie_set, entity2id):
    """
    Processes a data file, replaces movie IDs with names in text but stores entity IDs in lists.
    """
    with open(data_file, 'r', encoding='utf-8') as fin, open(out_file, 'w', encoding='utf-8') as fout:
        for line in tqdm(fin):
            dialog = json.loads(line)
            if len(dialog['messages']) == 0:
                continue

            movieid2name = dialog['movieMentions']
            user_id, resp_id = dialog['initiatorWorkerId'], dialog['respondentWorkerId']
            context, resp = [], ''
            entity_list = []  # Will store IDs instead of names
            messages = dialog['messages']
            turn_i = 0
            
            while turn_i < len(messages):
                worker_id = messages[turn_i]['senderWorkerId']
                utt_turn = []
                entity_turn = []
                movie_turn = []

                turn_j = turn_i
                while turn_j < len(messages) and messages[turn_j]['senderWorkerId'] == worker_id:
                    utt = process_utt(messages[turn_j]['text'], movieid2name, replace_movieId=True)
                    utt_turn.append(utt)

                    # Match entities and store their IDs
                    entity_ids = [
                        match_entity_by_name(entity, entity2id)
                        for entity in messages[turn_j]['entity']
                    ]
                    entity_turn.extend([eid for eid in entity_ids if eid is not None])

                    # Match movies and store their IDs
                    movie_ids = [
                        match_entity_by_name(movie, entity2id)
                        for movie in messages[turn_j]['movie']
                    ]
                    movie_turn.extend([mid for mid in movie_ids if mid is not None])

                    turn_j += 1

                utt = ' '.join(utt_turn)
                resp = utt

                # Flatten and deduplicate entity IDs from context
                context_entity_list = [entity for entity_l in entity_list for entity in entity_l]
                context_entity_list = list(set(context_entity_list))

                if len(context) == 0:
                    context.append('')

                turn = {
                    'context': context,
                    'resp': resp,
                    'rec': list(set(movie_turn + entity_turn)),  # Store unique IDs
                    'entity': context_entity_list,  # Store IDs from context
                }
                fout.write(json.dumps(turn, ensure_ascii=False) + '\n')

                context.append(resp)
                entity_list.append(movie_turn + entity_turn)
                movie_set |= set(movie_turn)

                turn_i = turn_j

if __name__ == '__main__':
    with open('/home/Nema/UniCRS_GraphRAG/GraphRAG/entity2id.json', 'r', encoding='utf-8') as f:
        entity2id = json.load(f)

    item_set = set()

    # Process files
    process('/home/Nema/UniCRS_GraphRAG/data/redial/valid_data_dbpedia.jsonl', 
           '/home/Nema/UniCRS_GraphRAG/UniCRS/data/redialv/alid_data_dbpedia_processed.jsonl', 
           item_set,
           entity2id)
    
    process('/home/Nema/UniCRS_GraphRAG/data/redial/test_data_dbpedia.jsonl', 
           '/home/Nema/UniCRS_GraphRAG/UniCRS/data/redial/test_data_dbpedia_processed.jsonl', 
           item_set,
           entity2id)
    
    process('/home/Nema/UniCRS_GraphRAG/data/redial/valid_data_dbpedia.jsonl', 
           '/home/Nema/UniCRS_GraphRAG/UniCRS/data/redial/train_data_dbpedia_processed.jsonl', 
           item_set,
           entity2id)

    # Save item IDs
    with open('/home/Nema/UniCRS_GraphRAG/UniCRS/data/redial/item_ids.json', 'w', encoding='utf-8') as f:
        json.dump(list(item_set), f, ensure_ascii=False)

    print(f'#item: {len(item_set)}')

/home/Nema/miniconda3/envs/graphrag/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

FileNotFoundError: [Errno 2] No such file or directory: '/home/Nema/UniCRS_GraphRAG/data/redial/valid_data_dbpedia.jsonl'

In [1]:
import json
import re
import html
from tqdm.auto import tqdm

# Regular expression to match movie IDs in text
movie_pattern = re.compile(r'@\d+')

def simplify_and_normalize(name):
    """Simplifies and normalizes entity or movie names."""
    name = name.replace("_", " ").lower()
    name = re.sub(r"\s*\(.*?\)", "", name).strip()
    return name

def match_entity_by_name(name, entity_name_map):
    """Find a matching entity in entity_name_map using substring matching."""
    simplified_name = simplify_and_normalize(name)
    for entity in entity_name_map:
        normalized_entity = simplify_and_normalize(entity)
        if simplified_name in normalized_entity:  # Substring matching
            return entity
    return None

def replace_entity_ids_in_text(text, entity_map):
    """
    Replaces entity IDs in the text with the corresponding entity names.

    Args:
        text (str): The input text with entity references.
        entity_map (dict): Mapping of entity IDs to entity names.

    Returns:
        str: The text with entity IDs replaced by entity names.
    """
    def replace_entity(match):
        entity_id = match.group(0)[1:]  # Remove '@' prefix
        return entity_map.get(entity_id, match.group(0))  # Replace if found, else keep original

    return re.sub(movie_pattern, replace_entity, text)

def process(data_file, out_file, movie_set, entity2id):
    """
    Processes a data file, replaces movie/entity IDs with names in text, and matches entities/movies by names.

    Args:
        data_file (str): Path to the input JSONL file.
        out_file (str): Path to the output JSONL file.
        movie_set (set): Set to store matched movie names.
        entity2id (dict): Mapping of entity names to IDs.
    """
    with open(data_file, 'r', encoding='utf-8') as fin, open(out_file, 'w', encoding='utf-8') as fout:
        for line in tqdm(fin):
            dialog = json.loads(line)
            if len(dialog['messages']) == 0:
                continue

            movieid2name = dialog['movieMentions']
            context, resp = [], ''
            entity_list = []
            messages = dialog['messages']
            turn_i = 0
            while turn_i < len(messages):
                worker_id = messages[turn_i]['senderWorkerId']
                utt_turn = []
                entity_turn = []
                movie_turn = []

                turn_j = turn_i
                while turn_j < len(messages) and messages[turn_j]['senderWorkerId'] == worker_id:
                    # Replace entity IDs in text
                    text_with_entities = replace_entity_ids_in_text(
                        messages[turn_j]['text'], {v: k for k, v in entity2id.items()}
                    )
                    utt_turn.append(text_with_entities)

                    # Match entities by name using substring logic
                    entity_names = [
                        match_entity_by_name(entity, entity2id)
                        for entity in messages[turn_j]['entity']
                        if match_entity_by_name(entity, entity2id) is not None
                    ]
                    entity_turn.extend(entity_names)

                    # Match movies by name using substring logic
                    movie_names = [
                        match_entity_by_name(movie, entity2id)
                        for movie in messages[turn_j]['movie']
                        if match_entity_by_name(movie, entity2id) is not None
                    ]
                    movie_turn.extend(movie_names)

                    turn_j += 1

                utt = ' '.join(utt_turn)

                resp = utt

                context_entity_list = [entity for entity_l in entity_list for entity in entity_l]
                context_entity_list = list(set(context_entity_list))

                if len(context) == 0:
                    context.append('')

                turn = {
                    'context': context,
                    'resp': resp,
                    'rec': list(set(movie_turn + entity_turn)),
                    'entity': context_entity_list,
                }
                fout.write(json.dumps(turn, ensure_ascii=False) + '\n')

                context.append(resp)
                entity_list.append(movie_turn + entity_turn)
                movie_set |= set(movie_turn)

                turn_i = turn_j


if __name__ == '__main__':
    with open('/home/Nema/UniCRS_GraphRAG/GraphRAG/entity2id.json', 'r', encoding='utf-8') as f:
        entity2id = json.load(f)

    item_set = set()

    process('/home/Nema/UniCRS_GraphRAG/data/redial/test_data_dbpedia.jsonl', '/home/Nema/UniCRS_GraphRAG/GraphRAG/test_data_dbpedia_processed.jsonl', item_set, entity2id)
    process('/home/Nema/UniCRS_GraphRAG/data/redial/valid_data_dbpedia.jsonl', '/home/Nema/UniCRS_GraphRAG/GraphRAG/valid_data_dbpedia_processed.jsonl', item_set, entity2id)
    process('/home/Nema/UniCRS_GraphRAG/data/redial/train_data_dbpedia.jsonl', '/home/Nema/UniCRS_GraphRAG/GraphRAG/train_data_dbpedia_processed.jsonl', item_set, entity2id)

    with open('/home/Nema/UniCRS_GraphRAG/GraphRAG/item_ids_2.json', 'w', encoding='utf-8') as f:
        json.dump(list(item_set), f, ensure_ascii=False)

    print(f'#item: {len(item_set)}')

0it [00:00, ?it/s]

0it [00:00, ?it/s]

0it [00:00, ?it/s]